# Preâmbulo Geral
project:
  type: book
  output-dir: docs

book:
  title: "Fundamentos de Estatística "
  page-footer:
    left: |
      Was Written by (VALENTE e TAVARES - 2024).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  subtitle: "**Na Gestão Pública Paraense**"
  author: 
  - name: "**Mário Diego Rocha Valente**"
    orcid: 0000-0001-7262-3336
    #corresponding: true
    #email: diego.vatente@gmail.com
  - name: "**Heliton Ribeiro Tavares**"
    orcid: 0000-0003-1725-3664
  date: "02/04/2024"
  search: true
  repo-url: https://github.com/MarioDhiego/Book_Estatistica_Quarto
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - Tabelas.qmd
    - Graficos.qmd
    - references.qmd
comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: 
      light: [pulse,custom.scss]
      dark:  [cyborg,custom.scss]
    toc-title: Índice
    toc-location: right
  pdf:
    documentclass: scrreprt
    fig-pos: "H"
    number-sections: true
    pdf-engine: xelatex
    fontsize: 12pt
  epub:
    cover-image: cover.png
abstract: "O Livro Fundamentos de Estatística na Gestão Pública Paraense esta dividivo em 4 capítulos, contemplando os conceitos fundamentais de Estatítica, as principais regras de representação tabular e grafica, detalhando os principais métodos de amostragem e, as medidas mais utilizadas em relatórios na area publica, tais como: média, moda, mediana e quartis."

lang: pt
